// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `endpoint.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <endpoint.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __EndPointCtrl__EndPointCtrlInt__AddPairs_name = "AddPairs";

const ::std::string __EndPointCtrl__EndPointCtrlInt__DelPairs_name = "DelPairs";

const ::std::string __EndPointCtrl__EndPointCtrlInt__GetResults_name = "GetResults";

const ::std::string __EndPointCtrl__EndPointCtrlInt__Ep2AddPairs_name = "Ep2AddPairs";

const ::std::string __EndPointCtrl__EndPointCtrlInt__Ep2DelPairs_name = "Ep2DelPairs";

const ::std::string __EndPointCtrl__EndPointCtrlInt__Ep2GetResults_name = "Ep2GetResults";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::EndPointCtrl::upCast(::IceProxy::EndPointCtrl::EndPointCtrlInt* p) { return p; }

void
::IceProxy::EndPointCtrl::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::EndPointCtrl::EndPointCtrlInt>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::EndPointCtrl::EndPointCtrlInt;
        v->__copyFrom(proxy);
    }
}

::EndPointCtrl::QaddPairResult
IceProxy::EndPointCtrl::EndPointCtrlInt::AddPairs(const ::EndPointCtrl::Qpair& pairlist, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __EndPointCtrl__EndPointCtrlInt__AddPairs_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__EndPointCtrl__EndPointCtrlInt__AddPairs_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::EndPointCtrl::EndPointCtrlInt* __del = dynamic_cast< ::IceDelegate::EndPointCtrl::EndPointCtrlInt*>(__delBase.get());
            return __del->AddPairs(pairlist, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::EndPointCtrl::EndPointCtrlInt::begin_AddPairs(const ::EndPointCtrl::Qpair& pairlist, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__EndPointCtrl__EndPointCtrlInt__AddPairs_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __EndPointCtrl__EndPointCtrlInt__AddPairs_name, __del, __cookie);
    try
    {
        __result->__prepare(__EndPointCtrl__EndPointCtrlInt__AddPairs_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(pairlist);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::EndPointCtrl::QaddPairResult
IceProxy::EndPointCtrl::EndPointCtrlInt::end_AddPairs(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __EndPointCtrl__EndPointCtrlInt__AddPairs_name);
    ::EndPointCtrl::QaddPairResult __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

void
IceProxy::EndPointCtrl::EndPointCtrlInt::DelPairs(const ::EndPointCtrl::QGetResultUuid& uuidlist, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __EndPointCtrl__EndPointCtrlInt__DelPairs_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::EndPointCtrl::EndPointCtrlInt* __del = dynamic_cast< ::IceDelegate::EndPointCtrl::EndPointCtrlInt*>(__delBase.get());
            __del->DelPairs(uuidlist, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::EndPointCtrl::EndPointCtrlInt::begin_DelPairs(const ::EndPointCtrl::QGetResultUuid& uuidlist, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __EndPointCtrl__EndPointCtrlInt__DelPairs_name, __del, __cookie);
    try
    {
        __result->__prepare(__EndPointCtrl__EndPointCtrlInt__DelPairs_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(uuidlist);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::EndPointCtrl::EndPointCtrlInt::end_DelPairs(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __EndPointCtrl__EndPointCtrlInt__DelPairs_name);
}

::EndPointCtrl::QpairStatsList
IceProxy::EndPointCtrl::EndPointCtrlInt::GetResults(const ::EndPointCtrl::QGetResultUuid& uuidlist, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __EndPointCtrl__EndPointCtrlInt__GetResults_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__EndPointCtrl__EndPointCtrlInt__GetResults_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::EndPointCtrl::EndPointCtrlInt* __del = dynamic_cast< ::IceDelegate::EndPointCtrl::EndPointCtrlInt*>(__delBase.get());
            return __del->GetResults(uuidlist, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::EndPointCtrl::EndPointCtrlInt::begin_GetResults(const ::EndPointCtrl::QGetResultUuid& uuidlist, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__EndPointCtrl__EndPointCtrlInt__GetResults_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __EndPointCtrl__EndPointCtrlInt__GetResults_name, __del, __cookie);
    try
    {
        __result->__prepare(__EndPointCtrl__EndPointCtrlInt__GetResults_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(uuidlist);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::EndPointCtrl::QpairStatsList
IceProxy::EndPointCtrl::EndPointCtrlInt::end_GetResults(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __EndPointCtrl__EndPointCtrlInt__GetResults_name);
    ::EndPointCtrl::QpairStatsList __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

::EndPointCtrl::QaddPairResult
IceProxy::EndPointCtrl::EndPointCtrlInt::Ep2AddPairs(const ::EndPointCtrl::Qpair& pairlist, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __EndPointCtrl__EndPointCtrlInt__Ep2AddPairs_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__EndPointCtrl__EndPointCtrlInt__Ep2AddPairs_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::EndPointCtrl::EndPointCtrlInt* __del = dynamic_cast< ::IceDelegate::EndPointCtrl::EndPointCtrlInt*>(__delBase.get());
            return __del->Ep2AddPairs(pairlist, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::EndPointCtrl::EndPointCtrlInt::begin_Ep2AddPairs(const ::EndPointCtrl::Qpair& pairlist, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__EndPointCtrl__EndPointCtrlInt__Ep2AddPairs_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __EndPointCtrl__EndPointCtrlInt__Ep2AddPairs_name, __del, __cookie);
    try
    {
        __result->__prepare(__EndPointCtrl__EndPointCtrlInt__Ep2AddPairs_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(pairlist);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::EndPointCtrl::QaddPairResult
IceProxy::EndPointCtrl::EndPointCtrlInt::end_Ep2AddPairs(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __EndPointCtrl__EndPointCtrlInt__Ep2AddPairs_name);
    ::EndPointCtrl::QaddPairResult __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

void
IceProxy::EndPointCtrl::EndPointCtrlInt::Ep2DelPairs(const ::EndPointCtrl::QGetResultUuid& uuidlist, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __EndPointCtrl__EndPointCtrlInt__Ep2DelPairs_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::EndPointCtrl::EndPointCtrlInt* __del = dynamic_cast< ::IceDelegate::EndPointCtrl::EndPointCtrlInt*>(__delBase.get());
            __del->Ep2DelPairs(uuidlist, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::EndPointCtrl::EndPointCtrlInt::begin_Ep2DelPairs(const ::EndPointCtrl::QGetResultUuid& uuidlist, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __EndPointCtrl__EndPointCtrlInt__Ep2DelPairs_name, __del, __cookie);
    try
    {
        __result->__prepare(__EndPointCtrl__EndPointCtrlInt__Ep2DelPairs_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(uuidlist);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::EndPointCtrl::EndPointCtrlInt::end_Ep2DelPairs(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __EndPointCtrl__EndPointCtrlInt__Ep2DelPairs_name);
}

::EndPointCtrl::QpairStatsList
IceProxy::EndPointCtrl::EndPointCtrlInt::Ep2GetResults(const ::EndPointCtrl::QGetResultUuid& uuidlist, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __EndPointCtrl__EndPointCtrlInt__Ep2GetResults_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__EndPointCtrl__EndPointCtrlInt__Ep2GetResults_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::EndPointCtrl::EndPointCtrlInt* __del = dynamic_cast< ::IceDelegate::EndPointCtrl::EndPointCtrlInt*>(__delBase.get());
            return __del->Ep2GetResults(uuidlist, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::EndPointCtrl::EndPointCtrlInt::begin_Ep2GetResults(const ::EndPointCtrl::QGetResultUuid& uuidlist, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__EndPointCtrl__EndPointCtrlInt__Ep2GetResults_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __EndPointCtrl__EndPointCtrlInt__Ep2GetResults_name, __del, __cookie);
    try
    {
        __result->__prepare(__EndPointCtrl__EndPointCtrlInt__Ep2GetResults_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(uuidlist);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::EndPointCtrl::QpairStatsList
IceProxy::EndPointCtrl::EndPointCtrlInt::end_Ep2GetResults(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __EndPointCtrl__EndPointCtrlInt__Ep2GetResults_name);
    ::EndPointCtrl::QpairStatsList __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::EndPointCtrl::EndPointCtrlInt::ice_staticId()
{
    return ::EndPointCtrl::EndPointCtrlInt::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::EndPointCtrl::EndPointCtrlInt::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::EndPointCtrl::EndPointCtrlInt);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::EndPointCtrl::EndPointCtrlInt::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::EndPointCtrl::EndPointCtrlInt);
}

::IceProxy::Ice::Object*
IceProxy::EndPointCtrl::EndPointCtrlInt::__newInstance() const
{
    return new EndPointCtrlInt;
}

::EndPointCtrl::QaddPairResult
IceDelegateM::EndPointCtrl::EndPointCtrlInt::AddPairs(const ::EndPointCtrl::Qpair& pairlist, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __EndPointCtrl__EndPointCtrlInt__AddPairs_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(pairlist);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::EndPointCtrl::QaddPairResult __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateM::EndPointCtrl::EndPointCtrlInt::DelPairs(const ::EndPointCtrl::QGetResultUuid& uuidlist, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __EndPointCtrl__EndPointCtrlInt__DelPairs_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(uuidlist);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

::EndPointCtrl::QpairStatsList
IceDelegateM::EndPointCtrl::EndPointCtrlInt::GetResults(const ::EndPointCtrl::QGetResultUuid& uuidlist, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __EndPointCtrl__EndPointCtrlInt__GetResults_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(uuidlist);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::EndPointCtrl::QpairStatsList __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::EndPointCtrl::QaddPairResult
IceDelegateM::EndPointCtrl::EndPointCtrlInt::Ep2AddPairs(const ::EndPointCtrl::Qpair& pairlist, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __EndPointCtrl__EndPointCtrlInt__Ep2AddPairs_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(pairlist);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::EndPointCtrl::QaddPairResult __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateM::EndPointCtrl::EndPointCtrlInt::Ep2DelPairs(const ::EndPointCtrl::QGetResultUuid& uuidlist, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __EndPointCtrl__EndPointCtrlInt__Ep2DelPairs_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(uuidlist);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

::EndPointCtrl::QpairStatsList
IceDelegateM::EndPointCtrl::EndPointCtrlInt::Ep2GetResults(const ::EndPointCtrl::QGetResultUuid& uuidlist, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __EndPointCtrl__EndPointCtrlInt__Ep2GetResults_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(uuidlist);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::EndPointCtrl::QpairStatsList __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::EndPointCtrl::QaddPairResult
IceDelegateD::EndPointCtrl::EndPointCtrlInt::AddPairs(const ::EndPointCtrl::Qpair& pairlist, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::EndPointCtrl::QaddPairResult& __result, const ::EndPointCtrl::Qpair& __p_pairlist, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_pairlist(__p_pairlist)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::EndPointCtrl::EndPointCtrlInt* servant = dynamic_cast< ::EndPointCtrl::EndPointCtrlInt*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->AddPairs(_m_pairlist, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::EndPointCtrl::QaddPairResult& _result;
        const ::EndPointCtrl::Qpair& _m_pairlist;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __EndPointCtrl__EndPointCtrlInt__AddPairs_name, ::Ice::Normal, __context);
    ::EndPointCtrl::QaddPairResult __result;
    try
    {
        _DirectI __direct(__result, pairlist, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

void
IceDelegateD::EndPointCtrl::EndPointCtrlInt::DelPairs(const ::EndPointCtrl::QGetResultUuid& uuidlist, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::EndPointCtrl::QGetResultUuid& __p_uuidlist, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_uuidlist(__p_uuidlist)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::EndPointCtrl::EndPointCtrlInt* servant = dynamic_cast< ::EndPointCtrl::EndPointCtrlInt*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->DelPairs(_m_uuidlist, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::EndPointCtrl::QGetResultUuid& _m_uuidlist;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __EndPointCtrl__EndPointCtrlInt__DelPairs_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(uuidlist, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::EndPointCtrl::QpairStatsList
IceDelegateD::EndPointCtrl::EndPointCtrlInt::GetResults(const ::EndPointCtrl::QGetResultUuid& uuidlist, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::EndPointCtrl::QpairStatsList& __result, const ::EndPointCtrl::QGetResultUuid& __p_uuidlist, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_uuidlist(__p_uuidlist)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::EndPointCtrl::EndPointCtrlInt* servant = dynamic_cast< ::EndPointCtrl::EndPointCtrlInt*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->GetResults(_m_uuidlist, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::EndPointCtrl::QpairStatsList& _result;
        const ::EndPointCtrl::QGetResultUuid& _m_uuidlist;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __EndPointCtrl__EndPointCtrlInt__GetResults_name, ::Ice::Normal, __context);
    ::EndPointCtrl::QpairStatsList __result;
    try
    {
        _DirectI __direct(__result, uuidlist, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::EndPointCtrl::QaddPairResult
IceDelegateD::EndPointCtrl::EndPointCtrlInt::Ep2AddPairs(const ::EndPointCtrl::Qpair& pairlist, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::EndPointCtrl::QaddPairResult& __result, const ::EndPointCtrl::Qpair& __p_pairlist, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_pairlist(__p_pairlist)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::EndPointCtrl::EndPointCtrlInt* servant = dynamic_cast< ::EndPointCtrl::EndPointCtrlInt*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->Ep2AddPairs(_m_pairlist, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::EndPointCtrl::QaddPairResult& _result;
        const ::EndPointCtrl::Qpair& _m_pairlist;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __EndPointCtrl__EndPointCtrlInt__Ep2AddPairs_name, ::Ice::Normal, __context);
    ::EndPointCtrl::QaddPairResult __result;
    try
    {
        _DirectI __direct(__result, pairlist, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

void
IceDelegateD::EndPointCtrl::EndPointCtrlInt::Ep2DelPairs(const ::EndPointCtrl::QGetResultUuid& uuidlist, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::EndPointCtrl::QGetResultUuid& __p_uuidlist, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_uuidlist(__p_uuidlist)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::EndPointCtrl::EndPointCtrlInt* servant = dynamic_cast< ::EndPointCtrl::EndPointCtrlInt*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->Ep2DelPairs(_m_uuidlist, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::EndPointCtrl::QGetResultUuid& _m_uuidlist;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __EndPointCtrl__EndPointCtrlInt__Ep2DelPairs_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(uuidlist, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::EndPointCtrl::QpairStatsList
IceDelegateD::EndPointCtrl::EndPointCtrlInt::Ep2GetResults(const ::EndPointCtrl::QGetResultUuid& uuidlist, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::EndPointCtrl::QpairStatsList& __result, const ::EndPointCtrl::QGetResultUuid& __p_uuidlist, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_uuidlist(__p_uuidlist)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::EndPointCtrl::EndPointCtrlInt* servant = dynamic_cast< ::EndPointCtrl::EndPointCtrlInt*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->Ep2GetResults(_m_uuidlist, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::EndPointCtrl::QpairStatsList& _result;
        const ::EndPointCtrl::QGetResultUuid& _m_uuidlist;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __EndPointCtrl__EndPointCtrlInt__Ep2GetResults_name, ::Ice::Normal, __context);
    ::EndPointCtrl::QpairStatsList __result;
    try
    {
        _DirectI __direct(__result, uuidlist, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Object* EndPointCtrl::upCast(::EndPointCtrl::EndPointCtrlInt* p) { return p; }

namespace
{
const ::std::string __EndPointCtrl__EndPointCtrlInt_ids[2] =
{
    "::EndPointCtrl::EndPointCtrlInt",
    "::Ice::Object"
};

}

bool
EndPointCtrl::EndPointCtrlInt::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__EndPointCtrl__EndPointCtrlInt_ids, __EndPointCtrl__EndPointCtrlInt_ids + 2, _s);
}

::std::vector< ::std::string>
EndPointCtrl::EndPointCtrlInt::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__EndPointCtrl__EndPointCtrlInt_ids[0], &__EndPointCtrl__EndPointCtrlInt_ids[2]);
}

const ::std::string&
EndPointCtrl::EndPointCtrlInt::ice_id(const ::Ice::Current&) const
{
    return __EndPointCtrl__EndPointCtrlInt_ids[0];
}

const ::std::string&
EndPointCtrl::EndPointCtrlInt::ice_staticId()
{
    return __EndPointCtrl__EndPointCtrlInt_ids[0];
}

::Ice::DispatchStatus
EndPointCtrl::EndPointCtrlInt::___AddPairs(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::EndPointCtrl::Qpair pairlist;
    __is->read(pairlist);
    __inS.endReadParams();
    ::EndPointCtrl::QaddPairResult __ret = AddPairs(pairlist, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
EndPointCtrl::EndPointCtrlInt::___DelPairs(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::EndPointCtrl::QGetResultUuid uuidlist;
    __is->read(uuidlist);
    __inS.endReadParams();
    DelPairs(uuidlist, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
EndPointCtrl::EndPointCtrlInt::___GetResults(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::EndPointCtrl::QGetResultUuid uuidlist;
    __is->read(uuidlist);
    __inS.endReadParams();
    ::EndPointCtrl::QpairStatsList __ret = GetResults(uuidlist, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
EndPointCtrl::EndPointCtrlInt::___Ep2AddPairs(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::EndPointCtrl::Qpair pairlist;
    __is->read(pairlist);
    __inS.endReadParams();
    ::EndPointCtrl::QaddPairResult __ret = Ep2AddPairs(pairlist, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
EndPointCtrl::EndPointCtrlInt::___Ep2DelPairs(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::EndPointCtrl::QGetResultUuid uuidlist;
    __is->read(uuidlist);
    __inS.endReadParams();
    Ep2DelPairs(uuidlist, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
EndPointCtrl::EndPointCtrlInt::___Ep2GetResults(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::EndPointCtrl::QGetResultUuid uuidlist;
    __is->read(uuidlist);
    __inS.endReadParams();
    ::EndPointCtrl::QpairStatsList __ret = Ep2GetResults(uuidlist, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __EndPointCtrl__EndPointCtrlInt_all[] =
{
    "AddPairs",
    "DelPairs",
    "Ep2AddPairs",
    "Ep2DelPairs",
    "Ep2GetResults",
    "GetResults",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
EndPointCtrl::EndPointCtrlInt::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__EndPointCtrl__EndPointCtrlInt_all, __EndPointCtrl__EndPointCtrlInt_all + 10, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __EndPointCtrl__EndPointCtrlInt_all)
    {
        case 0:
        {
            return ___AddPairs(in, current);
        }
        case 1:
        {
            return ___DelPairs(in, current);
        }
        case 2:
        {
            return ___Ep2AddPairs(in, current);
        }
        case 3:
        {
            return ___Ep2DelPairs(in, current);
        }
        case 4:
        {
            return ___Ep2GetResults(in, current);
        }
        case 5:
        {
            return ___GetResults(in, current);
        }
        case 6:
        {
            return ___ice_id(in, current);
        }
        case 7:
        {
            return ___ice_ids(in, current);
        }
        case 8:
        {
            return ___ice_isA(in, current);
        }
        case 9:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
EndPointCtrl::EndPointCtrlInt::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
EndPointCtrl::EndPointCtrlInt::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
EndPointCtrl::__patch(EndPointCtrlIntPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::EndPointCtrl::EndPointCtrlIntPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::EndPointCtrl::EndPointCtrlInt::ice_staticId(), v);
    }
}
